version: '3.8'

services:
  php-8.0:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.0"
    image: php-mecab:8.0
    volumes:
      - ./mecab:/workspace/mecab

  php-8.1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.1"
    image: php-mecab:8.1
    volumes:
      - ./mecab:/workspace/mecab

  php-8.2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.2"
    image: php-mecab:8.2
    volumes:
      - ./mecab:/workspace/mecab

  php-8.3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.3"
    image: php-mecab:8.3
    volumes:
      - ./mecab:/workspace/mecab

  php-8.4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.4"
    image: php-mecab:8.4
    volumes:
      - ./mecab:/workspace/mecab
